### PR TITLE
More papers for nested NER

### PR DESCRIPTION
**Pull request by LiyuanLucasLiu**
a recent EMNLP2018 paper for nested NER

### CODE REVIEW

**Comment by LiyuanLucasLiu** [comment]
- [A Neural Transition-based Model for Nested Mention Recognition](https://arxiv.org/pdf/1810.01808.pdf)

**Comment by LiyuanLucasLiu** [comment]
Actually, I'm not sure whether we should include this many Nested NER papers... Let's discuss tomorrow and see if that fits most people's interest :-)

**Comment by LiyuanLucasLiu** [comment]
[Neural Segmental Hypergraphs for Overlapping Mention Recognition](https://arxiv.org/abs/1810.01817)

**Review by yuzhimanhua — COMMENTED** [review]
LGTM

**Review by yuzhimanhua — COMMENTED** [review]
LGTM

**Pull request merged**
